import { useState } from "react";
import { FileText, FileDown, X, CheckCircle } from "lucide-react";
import { cn } from "../lib/utils";
import { useToast } from "../hooks/use-toast";

interface ExportDialogProps {
  isOpen: boolean;
  onClose: () => void;
  content: string;
  topic: string;
}

export const ExportDialog = ({ isOpen, onClose, content, topic }: ExportDialogProps) => {
  const [selectedFormat, setSelectedFormat] = useState<"pdf" | "word" | null>(null);
  const [isExporting, setIsExporting] = useState(false);
  const { toast } = useToast();

  if (!isOpen) return null;

  const exportAsPDF = () => {
    setIsExporting(true);
    
    // Create a simple HTML document for printing
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>Research: ${topic}</title>
          <style>
            body { font-family: Georgia, serif; max-width: 800px; margin: 0 auto; padding: 40px; line-height: 1.6; }
            h1 { color: #1a365d; border-bottom: 2px solid #4fd1c5; padding-bottom: 10px; }
            h2 { color: #2d3748; margin-top: 30px; }
            a { color: #319795; }
            li { margin: 8px 0; }
            .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; color: #718096; font-size: 12px; }
          </style>
        </head>
        <body>
          <h1>Research: ${topic}</h1>
          ${content.replace(/## /g, '<h2>').replace(/\n/g, '<br>').replace(/- /g, '• ')}
          <div class="footer">Generated by AI Research Agent • ${new Date().toLocaleDateString()}</div>
        </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
    
    setIsExporting(false);
    toast({
      title: "PDF Export Ready",
      description: "Your research has been prepared for PDF export.",
    });
    onClose();
  };

  const exportAsWord = () => {
    setIsExporting(true);
    
    // Create a downloadable HTML file that Word can open
    const htmlContent = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word'>
      <head><meta charset='utf-8'><title>Research: ${topic}</title></head>
      <body style="font-family: Calibri, sans-serif;">
        <h1 style="color: #1a365d;">Research: ${topic}</h1>
        ${content.replace(/## /g, '<h2 style="color: #2d3748;">').replace(/\n/g, '<br>').replace(/- /g, '• ')}
        <p style="margin-top: 40px; color: #718096; font-size: 10pt;">Generated by AI Research Agent • ${new Date().toLocaleDateString()}</p>
      </body>
      </html>
    `;
    
    const blob = new Blob([htmlContent], { type: 'application/msword' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `research-${topic.toLowerCase().replace(/\s+/g, '-')}.doc`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    setIsExporting(false);
    toast({
      title: "Word Document Downloaded",
      description: "Your research has been exported as a Word document.",
    });
    onClose();
  };

  const handleExport = () => {
    if (selectedFormat === 'pdf') {
      exportAsPDF();
    } else if (selectedFormat === 'word') {
      exportAsWord();
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-background/80 backdrop-blur-sm"
        onClick={onClose}
      />
      
      {/* Dialog */}
      <div className={cn(
        "relative w-full max-w-md glass-panel p-6",
        "animate-slide-up"
      )}>
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-muted-foreground hover:text-foreground transition-colors"
        >
          <X className="w-5 h-5" />
        </button>

        <h3 className="text-xl font-display font-semibold text-foreground mb-2">
          Export Research
        </h3>
        <p className="text-muted-foreground mb-6">
          Choose your preferred format to download the research.
        </p>

        <div className="space-y-3 mb-6">
          {/* PDF Option */}
          <button
            onClick={() => setSelectedFormat('pdf')}
            className={cn(
              "w-full flex items-center gap-4 p-4 rounded-lg border transition-all",
              selectedFormat === 'pdf'
                ? "border-primary bg-primary/10"
                : "border-border hover:border-border/80 hover:bg-secondary/30"
            )}
          >
            <div className={cn(
              "w-12 h-12 rounded-lg flex items-center justify-center",
              selectedFormat === 'pdf' ? "bg-primary/20" : "bg-secondary"
            )}>
              <FileText className={cn(
                "w-6 h-6",
                selectedFormat === 'pdf' ? "text-primary" : "text-muted-foreground"
              )} />
            </div>
            <div className="flex-1 text-left">
              <div className="font-medium text-foreground">PDF Document</div>
              <div className="text-sm text-muted-foreground">Best for printing and sharing</div>
            </div>
            {selectedFormat === 'pdf' && (
              <CheckCircle className="w-5 h-5 text-primary" />
            )}
          </button>

          {/* Word Option */}
          <button
            onClick={() => setSelectedFormat('word')}
            className={cn(
              "w-full flex items-center gap-4 p-4 rounded-lg border transition-all",
              selectedFormat === 'word'
                ? "border-primary bg-primary/10"
                : "border-border hover:border-border/80 hover:bg-secondary/30"
            )}
          >
            <div className={cn(
              "w-12 h-12 rounded-lg flex items-center justify-center",
              selectedFormat === 'word' ? "bg-primary/20" : "bg-secondary"
            )}>
              <FileDown className={cn(
                "w-6 h-6",
                selectedFormat === 'word' ? "text-primary" : "text-muted-foreground"
              )} />
            </div>
            <div className="flex-1 text-left">
              <div className="font-medium text-foreground">Word Document</div>
              <div className="text-sm text-muted-foreground">Best for editing and collaboration</div>
            </div>
            {selectedFormat === 'word' && (
              <CheckCircle className="w-5 h-5 text-primary" />
            )}
          </button>
        </div>

        <button
          onClick={handleExport}
          disabled={!selectedFormat || isExporting}
          className={cn(
            "w-full py-3 rounded-lg font-medium transition-all",
            "bg-primary text-primary-foreground",
            "hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed"
          )}
        >
          {isExporting ? "Exporting..." : "Export Now"}
        </button>
      </div>
    </div>
  );
};
